// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agxgohzgsoodqqbinybm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFneGdvaHpnc29vZHFxYmlueWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3NTA1ODcsImV4cCI6MjA1MzMyNjU4N30.amIaLZAnC8fLsz--7K_HY9NOHAbljKUaYnFebrVEhgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);